# Header
menu:
  #主页: /
  所有文章: /archives
  视频教程: /videos
  科技之星: /citstar
  作品: /works
  时间线: /timeline
  #简历-关于我: /aboutme


# SubNav
subnav:
  github: "https://github.com/icodeu"
  #weibo: "#"
  #rss: "#"
  #zhihu: "#"
  #douban: "#"
  mail: "mailto:icodeyou@sina.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: https://avatars1.githubusercontent.com/u/7385129?v=3&s=460
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: icodeyou
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  我大哥的博客: http://www.lynahex.com/
  牛B的学弟: http://zacharyjia.github.io/
  cdxy: http://www.cdxy.me/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 不断成长的 程序员